### ISSUE TITLE
Support Backblaze B2 as backend

### ISSUE THREAD

**Issue by tamalsaha** [appscode/stash#125]
If there are enough user request, we should add this.

**Comment by whereisaaron** [comment]
First thing I checked for when I was point at `stash` 😄

**Comment by tamalsaha** [comment]
@whereisaaron, will you help us test this? I don't have a B2 account. The code is mostly there.

**Comment by whereisaaron** [comment]
Yes, love too @tamalsaha . Can likely test this week and next, as I am testing some new automated cluster deployments (k8s 1.8). Point me at a test image ideally.
B2 accounts are free for the first 1 Gb and no credit card required to sign up. I think you just need to verify a phone number. But I'll be happy to test too. https://www.backblaze.com/b2/sign-up.html

**Comment by tamalsaha** [comment]
Can you try the new 0.6.0 release? Please check the instructions here: https://appscode.com/products/stash/0.6.0/guides/backends/

**Comment by whereisaaron** [comment]
Hi @tamalsaha, I am testing 0.6.1 with B2 on a k8s 1.8 cluster with RBAC.

Unfortunately the RBAC permission in the official/stable Helm chart don't see sufficient. See `operator` log below.

```
I0104 23:54:30.310281       1 logs.go:19] registry.ping url=https://registry-1.docker.io/v2/
I0104 23:54:30.522037       1 logs.go:19] registry.manifest.get url=https://registry-1.docker.io/v2/appscode/stash/manifests/0.6.1 repository=appscode/stash reference=0.6.1
W0104 23:54:30.742410       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0104 23:54:30.745102       1 logs.go:19] registry.ping url=https://registry-1.docker.io/v2/
I0104 23:54:30.866475       1 logs.go:19] registry.manifest.get url=https://registry-1.docker.io/v2/appscode/kubectl/manifests/1.8.0 repository=appscode/kubectl reference=1.8.0
F0104 23:54:34.104993       1 run.go:73] clusterroles.rbac.authorization.k8s.io "stash-sidecar" is forbidden: User "system:serviceaccount:backup:stash-backup" cannot get clusterroles.rbac.authorization.k8s.io at the cluster scope
```

This is what the Helm chart deploys for RBAC. Can you spot what is missing? Seems like it is after `clusterroles.rbac.authorization.k8s.io` but dosn't grant that to itself?

```
# Source: stash/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stash-backup
  labels:
    chart: "stash-0.2.0"
    app: "stash"
    heritage: "Tiller"
    release: "stash-backup"
---
# Source: stash/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: stash-backup
  labels:
    chart: "stash-0.2.0"
    app: "stash"
    heritage: "Tiller"
    release: "stash-backup"
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - "*"
- apiGroups:
  - stash.appscode.com
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - extensions
  resources:
  - replicasets
  - daemonsets
  verbs: ["get", "list", "watch", "patch"]
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources:
  - namespaces
  - replicationcontrollers
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", delete"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs: ["get", "create", "delete", "patch"]
---
# Source: stash/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: stash-backup
  labels:
    chart: "stash-0.2.0"
    app: "stash"
    heritage: "Tiller"
    release: "stash-backup"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stash-backup
subjects:
- kind: ServiceAccount
  name: stash-backup
  namespace: backup
```
