### ISSUE TITLE
Kops + AWS: cannot unmarshal array into Go value of type types.ContainerJSON

### ISSUE THREAD

**Issue by Rastusik** [appscode/stash#147]
After trying to run Restic object in AWS (deployed by Kops), I'm getting this error:

```
to get container status {"" ""}: rpc error: code = 2 desc = json: cannot unmarshal array into Go value of type types.ContainerJSON
```

It's the only message in the logs and the container terminates with error.

This is my Restic object definition:

```yaml
kind: Restic
apiVersion: stash.appscode.com/v1alpha1
metadata:
  name: jenkins-restic
  namespace: code-vault
spec:
  selector:
    matchLabels:
      run: jenkins
  fileGroups:
  - path: /var/jenkins_home
    retentionPolicy:
      keepLast: 10
      prune: true
  backend:
    s3:
      endpoint: 's3.amazonaws.com'
      bucket: whatever
      prefix: jenkins-demo
    storageSecretName: restic-s3-secret
  schedule: '@midnight'
  volumeMounts:
  - mountPath: /var/jenkins_home
    name: jenkins-data
    subPath: jenkins
```

Any suggestions?

**Comment by tamalsaha** [comment]
Thanks for reporting the issue. What is the version of your Kubernetes cluster? Can you also show the YAML for the actual Jenkins object?

**Comment by Rastusik** [comment]
kubernetes version: v1.7.3

jenkins deployment yaml:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: jenkins
    name: jenkins
  name: jenkins
  namespace: code-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: jenkins
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: failure-domain.beta.kubernetes.io/zone
                operator: In
                values:
                - eu-west-1c
      containers:
      - image: domain.tld/jenkins/jenkins-master:2.60.2
        imagePullPolicy: Always
        name: jenkins
        env:
        # enables multiple slave executors
        - name: JAVA_OPTS
          value: "-Dhudson.slaves.NodeProvisioner.initialDelay=100 -Dhudson.slaves.NodeProvisioner.recurrencePeriod=500 -Dhudson.slaves.NodeProvisioner.MARGIN=100"
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 1
            memory: 2Gi
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-data
          mountPath: "/var/jenkins_home"
          subPath: 'jenkins'
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-master-pvc
      imagePullSecrets:
      - name: docker-image-pull-secret
```
