### ISSUE TITLE
Unable to use non-aws S3 backend

### ISSUE THREAD

**Issue by RonnyMaas** [appscode/stash#226]
I configured a non-aws s3 backend (Ceph Object Gateway S3 API) for snapshot backups.
But It's not working and stash has the following errors.

```
[golang-sh]$ /bin/restic snapshots --json
unable to open repo at s3:/: minio.NewWithCredentials: Endpoint:  does not follow ip address or domain name standards.
[golang-sh]$ /bin/restic init
create backend at s3:/ failed: open: minio.NewWithCredentials: Endpoint:  does not follow ip address or domain name standards.
I1114 10:40:44.016211       1 scheduler.go:157] exit status 1

```
My used configurations for s3 backends are:
- In ./docs/examples/tutorial/restic.yaml

```
  backend:
    s3:
      path: /safe/data
      volumeSource:
        emptyDir: {}

```
- In ./docs/examples/backends/s3/s3-restic.yaml
```
   backend:
    s3:
      endpoint: 'https://objects.somedomain.com'
      bucket: 'backups'
      #prefix: demo
    storageSecretName: s3-secret

```
- kubernetes 1.7.5 resources
```
kubectl get all
NAME                             READY     STATUS    RESTARTS   AGE
po/stash-demo-2426073712-95sw1   2/2       Running   0          32m
NAME             CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
svc/kubernetes   10.3.0.1     <none>        443/TCP   9d
NAME                DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/stash-demo   1         1         1            1           1h
NAME                       DESIRED   CURRENT   READY     AGE
rs/stash-demo-1279072540   0         0         0         1h
rs/stash-demo-2426073712   1         1         1         32m
```

```
kubectl get secret
NAME                                TYPE                                  DATA      AGE
default-token-cfzcx                 kubernetes.io/service-account-token   3         9d
s3-secret                           Opaque                                3         1h
stash-demo                          Opaque                                1         1h
```

```
kubectl get restic stash-demo
NAME         KIND
stash-demo   Restic.v1alpha1.stash.appscode.com
```

```
kubectl get restic s3-restic
NAME        KIND
s3-restic   Restic.v1alpha1.stash.appscode.com

```
the s3 url is correct and bucket was already present before installing stash.

Am I missing something, is it a bug or not yet supported?
