### ISSUE TITLE
Error while running restic

### ISSUE THREAD

**Issue by xpowerman** [appscode/stash#256]
Hi. I make my own restic.

```
cat ./voipmonitor-restic.yaml 
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: voipmonitor-gui
  namespace: voipmonitor
spec:
  selector:
    matchLabels:
      app: voipmonitor-gui
  fileGroups:
  - path: /var/www
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      path: voipmonitor-gui
      volumeSource:
        hostPath:
          path: /mnt/backup/
    storageSecretName: voipmonitor-gui-restic
  schedule: '@every 5m'
  volumeMounts:
    name: voipmonitor-gui-rook
    mountPath: /var/www
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true
```

After kubectl apply -f ./voipmonitor-restic.yaml, i have errors in stash operator logs.
```
I1227 12:49:06.668763       1 reflector.go:236] Listing and watching *v1alpha1.Restic from github.com/appscode/stash/pkg/controller/controller.go:146
E1227 12:49:06.670161       1 reflector.go:201] github.com/appscode/stash/pkg/controller/controller.go:146: Failed to list *v1alpha1.Restic: only encoded map or array can be decoded into a struct
```

What does it mean? And how to solve this problem?
