### ISSUE TITLE
Recovery to PVC restores data in subdirectory instead of root directory

### ISSUE THREAD

**Issue by dzolotov** [appscode/stash#392]
The data was successfully backed up from PVC-attached block device, but after restore the files were placed in subdirectory with name, equals to last directory of original path, instead of original location. For example, if the original volume is mounted to /var/lib/grafana (from PVC), after recovery, the data is found in /var/lib/grafana/grafana.

Original restic yaml:
```yaml
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  namespace: monitoring
  name: kube-prometheus-grafana-restic
spec:
  selector:
    matchLabels:
      app: kube-prometheus-grafana
  fileGroups:
  - path: /var/lib/grafana
    retentionPolicyName: 'keep-last-30'
  backend:
    local:
      mountPath: /repo
      subPath: backups
      nfs:
        server: 10.245.245.10
        path: /
    storageSecretName: kube-prometheus-grafana-secret
  schedule: '@daily'
  volumeMounts:
  - mountPath: /var/lib/grafana
    name: grafana-storage
  retentionPolicies:
  - name: 'keep-last-30'
    keepLast: 30
    prune: true
```
Recovery YAML:
```yaml
apiVersion: stash.appscode.com/v1alpha1
kind: Recovery
metadata:
  name: kube-prometheus-grafana
  namespace: monitoring
spec:
  workload:
    kind: Deployment
    name: kube-prometheus-grafana
  backend:
    local:
      mountPath: /repo
      subPath: backups
      nfs:
        server: 10.245.245.10
        path: /
    storageSecretName: kube-prometheus-grafana-secret
  paths:
  - /var/lib/grafana
  recoveredVolumes:
  - mountPath: /var/lib/grafana
    persistentVolumeClaim:
      claimName: kube-prometheus-grafana
```
