### ISSUE TITLE
Incorrect image name for sidecar container

### ISSUE THREAD

**Issue by qwertys-ru** [appscode/stash#485]
Using stash helm chart from [appscode stable repo](https://charts.appscode.com/stable/).

After creating sidecar container from yaml (provided below) with `kubectl apply -f`, sidecar container has incorrect image name '/stash:0.7.0-rc.3' instead of 'appscode/stash:0.7.0-rc.3'. This yelds in ImgPullErr pod state.

Restic manifest:

```yaml
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: drone-srv-bak
  namespace: default
spec:
  selector:
    matchLabels:
      app: drone
      component: server
  fileGroups:
  - path: /var/lib/drone
    retentionPolicyName: 'keep-last-14'
  backend:
    s3:
      endpoint: 's3.amazonaws.com'
      bucket: k8s-stash
      prefix: internal
    storageSecretName: stash-s3
  schedule: '0 0 * * *'
  volumeMounts:
  - mountPath: /var/lib/drone
    name: data
  retentionPolicies:
  - name: 'keep-last-14'
    keepLast: 14
    prune: true
```

Resulting deployment yaml:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    restic.appscode.com/last-applied-configuration: |
      {"kind":"Restic","apiVersion":"stash.appscode.com/v1alpha1","metadata":{"name":"drone-srv-bak","namespace":"default","selfLink":"/apis/stash.appscode.com/v1alpha1/namespaces/default/restics/drone-srv-bak","uid":"fd2da2fc-5c51-11e8-96ec-0a222e1a3e74","resourceVersion":"6327739","creationTimestamp":"2018-05-20T17:19:44Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"stash.appscode.com/v1alpha1\",\"kind\":\"Restic\",\"metadata\":{\"annotations\":{},\"name\":\"drone-srv-bak\",\"namespace\":\"default\"},\"spec\":{\"backend\":{\"s3\":{\"bucket\":\"k8s-stash\",\"endpoint\":\"s3.amazonaws.com\",\"prefix\":\"internal\"},\"storageSecretName\":\"stash-s3\"},\"fileGroups\":[{\"path\":\"/var/lib/drone\",\"retentionPolicyName\":\"keep-last-14\"}],\"retentionPolicies\":[{\"keepLast\":14,\"name\":\"keep-last-14\",\"prune\":true}],\"schedule\":\"0 0 * * *\",\"selector\":{\"matchLabels\":{\"app\":\"drone\",\"component\":\"server\"}},\"volumeMounts\":[{\"mountPath\":\"/var/lib/drone\",\"name\":\"data\"}]}}\n"}},"spec":{"selector":{"matchLabels":{"app":"drone","component":"server"}},"fileGroups":[{"path":"/var/lib/drone","retentionPolicyName":"keep-last-14"}],"backend":{"storageSecretName":"stash-s3","s3":{"endpoint":"s3.amazonaws.com","bucket":"k8s-stash","prefix":"internal"}},"schedule":"0 0 * * *","volumeMounts":[{"name":"data","mountPath":"/var/lib/drone"}],"resources":{},"retentionPolicies":[{"name":"keep-last-14","keepLast":14,"prune":true}]}}
    restic.appscode.com/tag: 0.7.0-rc.3
  creationTimestamp: 2018-04-08T21:30:12Z
  generation: 5
  labels:
    app: drone
    chart: drone-0.4.2
    component: server
    heritage: Tiller
    release: cd
  name: cd-drone-server
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: drone
      component: server
      release: cd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/secrets: REDACTED
        restic.appscode.com/resource-hash: "REDACTED"
      creationTimestamp: null
      labels:
        app: drone
        component: server
        release: cd
    spec:
      containers:
      - env:
        - name: DRONE_SECRET
          valueFrom:
            secretKeyRef:
              key: secret
              name: REDACTED
        - name: DRONE_HOST
          value: REDACTED
        - name: DRONE_ADMIN
          value: REDACTED
        - name: DRONE_DATABASE_DATASOURCE
          value: /var/lib/drone/drone.sqlite
        - name: DRONE_DATABASE_DRIVER
          value: sqlite3
        - name: DRONE_DEBUG
          value: "false"
        - name: DRONE_PROVIDER
          value: github
        image: docker.io/drone/drone:0.8.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cd-drone-server
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 9000
          name: grpc
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/drone
          name: data
      - args:
        - backup
        - --restic-name=drone-srv-bak
        - --workload-kind=Deployment
        - --workload-name=cd-drone-server
        - --docker-registry=
        - --image-tag=0.7.0-rc.3
        - --run-via-cron=true
        - --pushgateway-url=http://stash-operator.default.svc:56789
        - --enable-analytics=true
        - --logtostderr=false
        - --alsologtostderr=false
        - --v=3
        - --stderrthreshold=0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: APPSCODE_ANALYTICS_CLIENT_ID
          value: REDACTED
        image: /stash:0.7.0-rc.3
        imagePullPolicy: IfNotPresent
        name: stash
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: stash-scratchdir
        - mountPath: /etc/stash
          name: stash-podinfo
        - mountPath: /var/lib/drone
          name: data
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: cd-drone
      - emptyDir: {}
        name: stash-scratchdir
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
        name: stash-podinfo
status:
  conditions:
  - lastTransitionTime: 2018-04-08T21:30:12Z
    lastUpdateTime: 2018-04-08T21:30:12Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-05-21T09:16:38Z
    lastUpdateTime: 2018-05-21T10:28:48Z
    message: ReplicaSet "cd-drone-server-57cd64d9ff" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 5
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```
