### ISSUE TITLE
matchLabels on Restic CRD not working when using hyphens in keys

### ISSUE THREAD

**Issue by arnadusable** [appscode/stash#521]
Tested on appscode/stash:0.7.0

When using hyphens in keys of the matchLabels features to select which pods to target with sidecars containers, nothing happens (no sidecars are created). 

I tested it with the redis-ha helm chart to target redis slave servers.

Below is a full example, pay attention to the keys "redis-node" and "redis-role".

```yaml
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: {{ .Release.Name }}-b2-restic-redis
spec:
  selector:
    matchLabels:
      app: {{ .Values.redis.nameOverride }}
      name: redis-server
      redis-node: server
      redis-role: slave
      release: {{ .Release.Name }}
  fileGroups:
  - path: /redis-master-data
    retentionPolicyName: 'keep-last-30'
  backend:
    b2:
      bucket: xxx
      prefix:
    storageSecretName: xxxx
  schedule: '@daily'
  volumeMounts:
  - mountPath: /redis-master-data
    name: data
  retentionPolicies:
  - name: 'keep-last-30'
    keepLast: 30
    prune: true
```

When removing problematic keys (in this exemple: "redis-node" and "redis-role") , stash works as expected.

**Comment by hossainemruz** [comment]
@arnadusable we don't see any problem with hyphen in `matchLabels`. We have tested in our setup and Stash is able to inject sidecar to them. Here, is our setup:

**Workload:**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stash-demo
    name: redis-server
    redis-node: server
    redis-role: slave
    release: "0.7"
  name: demo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stash-demo
  template:
    metadata:
      labels:
        app: stash-demo
      name: busybox
    spec:
      containers:
      - args:
        - sleep
        - "3600"
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /source/data
          name: source-data
      restartPolicy: Always
      volumes:
      - gitRepo:
          repository: https://github.com/appscode/stash-data.git
        name: source-data
```

**Restic:**
```yaml
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: stash-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: stash-demo
      name: redis-server
      redis-node: server
      redis-role: slave
      release: "0.7"
  fileGroups:
  - path: /source/data
    retentionPolicyName: keep-last-5
  backend:
    local:
      mountPath: /safe/data
      hostPath:
        path: /data/stash-test/restic-repo
    storageSecretName: local-secret
  schedule: '@every 1m'
  volumeMounts:
  - mountPath: /source/data
    name: source-data
  retentionPolicies:
  - name: keep-last-5
    keepLast: 5
    prune: true
```

Make sure your workload has all the specified labels in `matchLabels:` field.

>Note: Those label must be exist on your workload. Not necessarily on pods. For example, if you are using a StatefulSet, these lables must be in StatefulSet not necessarily in pods created by the StatefulSet.
