### ISSUE TITLE
Bad flag syntax when helm installing stash

### ISSUE THREAD

**Issue by GNewbury1** [appscode/stash#538]
When using the following command:
```shell
helm install appscode/stash --namespace kube-system --name stash-operator --version 0.7.0 \
  --set apiserver.ca="$(onessl get kube-ca)" \
  --set apiserver.enableValidatingWebhook=true \
  --set apiserver.enableMutatingWebhook=true
```
The following error is thrown:
```
Error: bad flag syntax: -----END
```
It looks as though this might have come about with the `$(onessl get kube-ca)` command, as the command spits out
```
-----BEGIN CERTIFICATE-----
<certificate>
-----END CERTIFICATE-----
```

Could the `-----END`  as part of `onessl get kube-ca` be the problem here? Any help on this would be appreciated!

### Binary versions
`onessl`: 0.7.0
`helm`: 2.9.1 (client and server)
`kubectl`: Client: 1.11, Server 1.9.7

**Comment by GNewbury1** [comment]
## Temporary workaround
Run `helm install --namespace kube-system appscode/stash --version 0.7.0 -f values.yaml -n stash-operator` with the following values.yaml:
```yaml
# Default values for stash.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
# Docker registry containing Stash images
operator:
  registry: appscode
  repository: stash
  tag: 0.7.0
pushgateway:
  registry: prom
  repository: pushgateway
  tag: v0.4.0
## Optionally specify an array of imagePullSecrets.
## Secrets must be manually created in the namespace.
## ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
##
# imagePullSecrets:
#   - name: myRegistryKeySecretName
## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent
## Installs Stash operator as critical addon
## https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
criticalAddon: false

## Install Default RBAC roles and bindings
rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

apiserver:
  # groupPriorityMinimum is the minimum priority the group should have. Please see
  # https://github.com/kubernetes/kube-aggregator/blob/release-1.9/pkg/apis/apiregistration/v1beta1/types.go#L58-L64
  # for more information on proper values of this field.
  groupPriorityMinimum: 10000
  # versionPriority is the ordering of this API inside of the group. Please see
  # https://github.com/kubernetes/kube-aggregator/blob/release-1.9/pkg/apis/apiregistration/v1beta1/types.go#L66-L70
  # for more information on proper values of this field
  versionPriority: 15
  # enableMutatingWebhook is used to configure mutating webhook for Kubernetes workloads
  enableMutatingWebhook: true
  # enableValidatingWebhook is used to configure validating webhook for Stash CRDss
  enableValidatingWebhook: true
  # CA certificate used by main Kubernetes api server
  ca: <INSERT CERTIFICATE HERE>
  # If true, uses status sub resource for crds.
  enableStatusSubresource: false

# Send usage events to Google Analytics
enableAnalytics: true
```
