### ISSUE TITLE
Stash taking complete PV backup instead of just taking the subpath

### ISSUE THREAD

**Issue by arjunsbabu** [appscode/stash#580]
Hi Team,

 I have created two deployments with same PV but two different subpath. 

Deployment 1 yaml 

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arjun
  template:
    metadata:
      labels:
        app: arjun
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webdirectory
          mountPath: /usr/share/nginx/html
          subPath: nginx-deploy1-path
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: webdirectory
        persistentVolumeClaim:
          claimName: nginxpv1`

Deployment 2 yaml

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arjun
  template:
    metadata:
      labels:
        app: arjun
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webdirectory
          mountPath: /usr/share/nginx/html
          subPath: nginx-deploy2-path
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: webdirectory
        persistentVolumeClaim:
          claimName: nginxpv1`

Then I created a restic to take backup of deployment one 

Restic yaml 

`apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: deploy1
spec:
  selector:
    matchLabels:
      place: deploy1
  fileGroups:
  - path: /usr/share/nginx/html
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      mountPath: /safe/data
      hostPath:
        path: /stash/pvtest
    storageSecretName: stash-demo
  schedule: '@every 1m'
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
  volumeMounts:
  - name: webdirectory
    mountPath: /usr/share/nginx/html
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true`

So I tried a manual restore to a different file path and I can see the whole PV got restore which have all the two subpaths

**Comment by hossainemruz** [comment]
@arjunsbabu can you please paste the yaml in following format so they don't lose indentation? It hard to read without indentation.

\```
\<your yaml here\>
\```

**Comment by arjunsbabu** [comment]
root@gyfradgicpdevm01:/stash/arjun/deployment/nginxdeploy# restic -r /stash/pvtest/deployment/nginx-deploy-1/ snapshots
repository 45f26e78 opened successfully, password is correct
ID        Date                 Host            Tags        Directory
----------------------------------------------------------------------
ebe9c965  2018-09-19 11:10:13  nginx-deploy-1              /usr/share/nginx/html
dc8a4d50  2018-09-19 11:11:13  nginx-deploy-1              /usr/share/nginx/html
3d57dae9  2018-09-19 11:12:13  nginx-deploy-1              /usr/share/nginx/html
7fb60fbb  2018-09-19 11:13:13  nginx-deploy-1              /usr/share/nginx/html
85be8043  2018-09-19 11:14:13  nginx-deploy-1              /usr/share/nginx/html
----------------------------------------------------------------------
5 snapshots
root@gyfradgicpdevm01:/stash/arjun/deployment/nginxdeploy# restic -r /stash/pvtest/deployment/nginx-deploy-1/ restore 85be8043 --target /tmp
repository 45f26e78 opened successfully, password is correct
restoring <Snapshot 85be8043 of [/usr/share/nginx/html] at 2018-09-19 11:14:13.198652978 +0000 UTC by @nginx-deploy-1> to /tmp
root@gyfradgicpdevm01:/stash/arjun/deployment/nginxdeploy# cd /tmp
root@gyfradgicpdevm01:/tmp# ls
html
root@gyfradgicpdevm01:/tmp# cd html/
root@gyfradgicpdevm01:/tmp/html# ls
nginx-deploy1-path  nginx-deploy2-path
root@gyfradgicpdevm01:/tmp/html#

**Comment by arjunsbabu** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arjun
  template:
    metadata:
      labels:
        app: arjun
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webdirectory
          mountPath: /usr/share/nginx/html
          subPath: nginx-deploy1-path
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: webdirectory
        persistentVolumeClaim:
          claimName: nginxpv1
```

**Comment by arjunsbabu** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arjun
  template:
    metadata:
      labels:
        app: arjun
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webdirectory
          mountPath: /usr/share/nginx/html
          subPath: nginx-deploy2-path
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: webdirectory
        persistentVolumeClaim:
          claimName: nginxpv1

```

**Comment by arjunsbabu** [comment]
Im manually  restoring and checking one of the snapshots to check its content

![image](https://user-images.githubusercontent.com/29661675/45750557-1bc14000-bc2d-11e8-96c1-d1b5e4d82ff4.png)

While checking I can see that the restored data contain the backup of both the deployments which is not desired

**Comment by hossainemruz** [comment]
@arjunsbabu you also have to specify `subPath` in `volumeMounts` of Restic crd.
i.e.
```
volumeMounts:
- name: webdirectory
  mountPath: /usr/share/nginx/html
  subPath: nginx-deploy1-path
```
