### ISSUE TITLE
Hardcoded cleaner kubectl image in Helm chart

### ISSUE THREAD

**Issue by sebastien-prudhomme** [appscode/stash#583]
Hardcoded cleaner kubectl image in Helm chart prevents using an internal image registry

I suggest adding this in values.yaml:

```
cleaner:
  registry: appcode
  repository: kubectl
  tag: v1.11 
```

and using these values in the cleaner job yaml file.
