### ISSUE TITLE
Stash grafana dashboard json file not showing metrics

### ISSUE THREAD

**Issue by arjunsbabu** [appscode/stash#585]
Hi Team,
I have just followed the link [https://appscode.com/products/stash/0.7.0-rc.3/guides/monitoring/](url)
 to configure monitoring for the stash backup.

I have edited my promitheus configmap and added the following job as follows

````
      - job_name: stash
        static_configs:
        - targets:
          - "10.0.0.223:56789"
kind: ConfigMap
metadata:
  creationTimestamp: 2018-09-24T05:29:32Z
  labels:
    app: monitoring-prometheus
    chart: ibm-icpmonitoring-1.1.0

````

I can see the metrics is up in the promitheus 
<img width="892" alt="promitheus scrap" src="https://user-images.githubusercontent.com/29661675/45956913-60841700-c031-11e8-95dc-92fc73f28b2b.PNG">

Then I downloaded the dashboard json from the link [https://grafana.com/dashboards/4198](url)

But its not showing any metrics 

<img width="894" alt="stash dashboard1" src="https://user-images.githubusercontent.com/29661675/45957061-b8bb1900-c031-11e8-823e-365820fc29d7.PNG">

Now from suggestion from our team edited the json file and changed the value exported_namespace to namespace . Then some of the metrics is showing 
<img width="940" alt="stash dashboard2" src="https://user-images.githubusercontent.com/29661675/45957129-ed2ed500-c031-11e8-85c9-d1ecf14e29a0.PNG">

So I suspect the json file is wrong . So kindly check and update
