### ISSUE TITLE
Proposal: Recover in same volume

### ISSUE THREAD

**Issue by hossainemruz** [appscode/stash#600]
User want to recover data in the same volume he backed up.

**Use case:** User may accidentally delete data from current volume and want to recover them from backed up volume without creating a new volume and re-deploying workload.

**Idea:** We can use init container to recover(just like offline backup). Workload will restart and init container will recover data in the same volume.

**Comment by emedina** [comment]
Notice that as a workaround, this can be already achieved by using the same `PersistentVolume` claim name that was used to create the backup in the `restic` manifest, as long as no running Pod is using it:

```
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
...
  volumeMounts:
  - mountPath: /var/www/html/config
    name: html-dir
```

```
apiVersion: stash.appscode.com/v1alpha1
kind: Recovery
...
    recoveredVolumes:
    - mountPath: /var/www/html/config
      persistentVolumeClaim:
        claimName: matomo-html-dir
...
```
