### ISSUE TITLE
Proposal: Simplify Restic specification

### ISSUE THREAD

**Issue by hossainemruz** [appscode/stash#602]
Simplify Restic crd so that the yaml become self-explanatory. i.e.
```
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: stash-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: stash-demo
  backend:
    local:
      mountPath: /safe/data
      hostPath:
        path: /data/stash-test/restic-repo
    storageSecretName: stash-demo
  schedule: '@every 1m'
  targetVolumes:
  - name: vol-1
    mountPath: /source/data
    directories:
    - path: /source/data
      retentionPolicyName: 'keep-last-5'
  - name: vol-2
    mountPath: /source/data
    directories:
    - path: /source/data
      retentionPolicyName: 'keep-last-5'
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true
```
Here,few things has been changes
- `volumeMounts:`  renamed as `targetVolumes:`
- `fileGroups:` moved to individual volumes and renamed as `directories`
