### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by tamalsaha** [appscode/stash#616]
in _> CRD

out: Statefulset, Secret, Service + AppBinding

Vault / Database -> AppBinding

---------------------------------------------------

SidecarBackup | 

VolumeBackup , Diskbackup

crd: BackupJob
```
backup process: write backup to disk, upload
  -- init container[0] takes backup
  -- container[0] uploads
```
```
recover process: download, restore
  -- init container downloads
  -- container[0] restores
```
mysqldump -host | restic -r s3:mydb

Non-namespaced CRD: BackupTemplate, RecoveryTemplate
```
apiVersion: stash.appscode.com/v1alpha1
kind: BackupTemplate
metadata
  name: mysql-backup
spec:
  command:
    mysqldump -host {{.DBSVC}}:{{port}} | restic -r {{RepoName}}
```

-----------
```
apiVersion: stash.appscode.com/v1alpha1
kind: RecoveryTemplate
metadata
  name: mysql-recovery
spec:
  container:
    ----
  command:
    restic -r {{RepoName}} | mysqld -host {{.DBSVC}}:{{port}}
```
----------
```
apiVersion: stash.appscode.com/v1alpha1
kind: BackupJob
metadata
  name: gitlab-backup
  namespace: default
spec:
  backend:
    name: Repository-crd
    namespace: Repository-crd
  appRef:
    name: gitlab-db
    namespace: gitlab
  template:
    name: mysql-backup
    parameters:

  schedule:
    cron:
```
---------

BackupJob + (template) -> k8s:Job

Default backup for any workload.

---------
