### ISSUE TITLE
Can't restore backup on Persistent Volume (Ceph)

### ISSUE THREAD

**Issue by Gizmos777** [appscode/stash#735]
Hello. I can't recovery backup on Persistent Volume which bases on  ceph.
I created crd recovery:

```
apiVersion: stash.appscode.com/v1alpha1
kind: Recovery
metadata:
  name: local-recovery
  namespace: demo
spec:
  repository:
    name: deployment.stash-demo
    namespace: demo
  paths:
  - /source/data
  recoveredVolumes:
  - mountPath: /source/data
    persistentVolumeClaim:
      claimName: stash-recovered
```

But it doesn't finish and it is staying in phase - running

`local-recovery   demo                   deployment.stash-demo              Running   32m`

In logs of stash-operator:
```
I0409 13:53:12.104018       1 rolebinding.go:19] Creating RoleBinding demo/stash-recovery-local-recovery.
I0409 13:53:12.139792       1 recoveries.go:188] Recovery job created: stash-recovery-local-recovery
```
PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-recovered
  namespace: demo
  labels:
    app: stash-demo
spec:
  storageClassName: rbd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
```
