### ISSUE TITLE
Run stash as non root user

### ISSUE THREAD

**Issue by Gizmos777** [appscode/stash#748]
Hello. It probably run  the pods of stash as non root user? 
I use Pod Security Policy so users mustn't run pod as root. 
I added the user stash in the image.
```
FROM appscode/stash:0.8.3
RUN  addgroup -S stash && adduser -S stash -G stash
USER stash
```
But  i can't recovery  my files.
I get the errors:
```
Warning  FailedRecovery      5m    stash-recovery  failed to recover FileGroup /source/data, reason:     /usr/local/go/src/runtime/asm_amd64.s:2361
Warning  FailedRecovery      5m    stash-recovery  Failed to complete recovery local-recovery, reason:   /usr/local/go/src/runtime/asm_amd64.s:2361 
```

**Comment by Gizmos777** [comment]
I found a mistake

**Comment by hossainemruz** [comment]
@Gizmos777 There is some issue while running Stash as non-root user. For details, please visit this doc: https://github.com/appscode/stash/blob/psp/docs/guides/ownership.md

>This doc has not merged to master yet.

From next version Stash will run as non-root user by default. Restore process may run as root but it will be configurable.

**Comment by Gizmos777** [comment]
I am trying the first case from https://github.com/appscode/stash/blob/psp/docs/guides/ownership.md.
Original File Owner - root. Backup sidecar and Restore init-container user - stash, but i get the error:
```
Warning  FailedRecovery      5m    stash-recovery  failed to recover FileGroup /source/data, reason:     /usr/local/go/src/runtime/asm_amd64.s:2361
Warning  FailedRecovery      5m    stash-recovery  Failed to complete recovery local-recovery, reason:   /usr/local/go/src/runtime/asm_amd64.s:2361 
```

**Comment by hossainemruz** [comment]
@Gizmos777 can you try specifying numeric UID and GID for stash image?

```
FROM appscode/stash:0.8.3
RUN addgroup -g 1005 stash \
    && adduser -u 1005 -G stash -D stash
USER stash
```

**Comment by Gizmos777** [comment]
I have already tried specifiying numeric 1005, but I got same error again.

**Comment by hossainemruz** [comment]
Are you using `hostPath` as local backend?

**Comment by Gizmos777** [comment]
I am using Persistent Volume by ceph.
Recovery yaml:
```
apiVersion: stash.appscode.com/v1alpha1
kind: Recovery
metadata:
  name: local-recovery
  namespace: demo
spec:
  repository:
    name: deployment.stash-demo
    namespace: demo
  paths:
  - /source/data
  recoveredVolumes:
  - mountPath: /source/data
    persistentVolumeClaim:
      claimName: stash-recovered
```
